language: python

python:
  - "3.4"

install:
  - pip install -r requirements_dev.txt
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

script:
  - pep8 pusher runtests
  - sudo rm -rf pusher
  - python -m runtests --coverage
  - python -m runtests --coveralls

notifications:
  email: false

branches:
  only:
    - master